#!/bin/bash

source scripts/config
source scripts/bootstrap
source scripts/update
source scripts/default

source scripts/usage
source scripts/version

if [[ $# -gt 0 ]] ; then
  token="$1" ; shift
  case "$token" in
    default)    __default $* ; exit ;;
    bootstrap)  __bootstrap $* ; exit ;;
    update)     __update $* ; exit ;;
    version)    __version ; exit ;;
    help|*)     __usage ;;
  esac
else
  __usage
fi