#!/bin/bash

__bootstrap() {
  echo -e ". Bootstrapping Servers..."

  while [[ $# -gt 0 ]] ; do
    server="$1" ; shift
    echo ".. ${server}..."

    ssh ${server} "$bootstrap_sh"
  done

  echo ". Done!"
}

bootstrap_sh='
command -v chef-solo >/dev/null && {
  echo ".. Chef Already Bootsrapped - skipping..."
  exit
}

echo ".. Installing Prerequisite Packages..."
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y build-essential git-core curl libssl-dev libxslt-dev libxml2-dev libreadline-dev zlib1g-dev
sudo apt-get install -y binutils-doc gcc autoconf flex bison libtool

echo ".. Installing Ruby 1.9.2"
sudo apt-get install -y ruby1.9.1 ruby1.9.1-dev rubygems1.9.1 irb1.9.1 ri1.9.1 rdoc1.9.1 libopenssl-ruby1.9.1

echo ".. Updating Ruby Alternatives"
sudo update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby1.9.1 400 \
         --slave   /usr/share/man/man1/ruby.1.gz ruby.1.gz \
                        /usr/share/man/man1/ruby1.9.1.1.gz \
        --slave   /usr/bin/ri ri /usr/bin/ri1.9.1 \
        --slave   /usr/bin/irb irb /usr/bin/irb1.9.1 \
        --slave   /usr/bin/rdoc rdoc /usr/bin/rdoc1.9.1 \
        --slave   /usr/bin/gem gem /usr/bin/gem1.9.1

sudo update-alternatives --config ruby
sudo update-alternatives --config gem

ohai_version=0.6.10
chef_version=0.10.8

echo ".. Installing Chef ..."
sudo gem install -v ${ohai_version} ohai --no-rdoc --no-ri
sudo gem install -v ${chef_version} chef --no-rdoc --no-ri
'