#!/bin/bash

# configuration
chef_file_dest=/tmp/chef

# db-ple-01
# (role)-(location)-(number)
hostname_regex='([a-z]+)\-([a-z0-9]+)\-([0-9]+)'

# versions for installations
rubygems_version=1.3.7
chef_version=0.9.8
ohai_version=0.5.6