#!/bin/bash

__update() {
  echo -e ". Updating Servers..."

  while [[ $# -gt 0 ]] ; do
    server="$1" ; shift
    echo ".. ${server}..."

    echo ".. Updating Cookbooks..."
    echo "... rsync -Caz --delete --exclude .git --rsh='ssh' ./ ${server}:${chef_file_dest}"
    rsync -Caz --delete --exclude .git --rsh='ssh' ./ ${server}:${chef_file_dest}

    echo ".. Running Chef Solo..."
    ssh ${server} "sudo chmod -R a+w /tmp/chef && sudo chef-solo -c ${chef_file_dest}/solo-config.rb -j ${chef_file_dest}/dna/${server}.json"
  done

  echo ". Done!"
}