#!/bin/bash

__update() {
  echo -e ". Updating Servers..."

  while [[ $# -gt 0 ]] ; do
    server="$1" ; shift
    echo ".. ${server}..."

    if [[ $server =~ $hostname_regex ]] ; then
      server_role=${BASH_REMATCH[1]}
      server_loc=${BASH_REMATCH[2]}
      server_num=${BASH_REMATCH[3]}

      server_env=dev

      echo ".. Updating Cookbooks..."
      rsync -Caz --delete --exclude .git --rsh='ssh' ./ ${server}:${chef_file_dest}

      echo ".. Running Chef Solo..."
      ssh ${server} "chef-solo -c ${chef_file_dest}/solo.rb -j ${chef_file_dest}/dna/${server_env}/${server_role}.json"
    else
      echo ".. Invalid Server Name - skipping..."
    fi
  done

  echo ". Done!"
}