#!/bin/bash

__update() {
  echo -e ". Updating Servers..."

  while [[ $# -gt 0 ]] ; do
    server="$1" ; shift
    echo ".. ${server}..."

    if [[ $server =~ $hostname_regex ]] ; then
      server_role=${BASH_REMATCH[1]}
      server_loc=${BASH_REMATCH[2]}
      server_num=${BASH_REMATCH[3]}

      echo ".. Updating Cookbooks..."
      rsync -Caz --delete --exclude .git --rsh='ssh' ./ ${server}:${chef_file_dest}
      sudo chmod -R a+w /tmp/chef

      echo ".. Running Chef Solo..."
      ssh ${server} "sudo chef-solo -c ${chef_file_dest}/solo-config.rb -j ${chef_file_dest}/dna/${server_role}-${server_loc}-${server_num}.json"
    else
      echo ".. Invalid Server Name - skipping..."
    fi
  done

  echo ". Done!"
}